apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  #ключ и значение через | (все что после черты - текст). Это волюм для nginx,
  #который возвращает 200 статус, имя configmap (my-configmap)
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;
    
      default_type text/plain;
    
      location / {
        return 200 'MY-CONFIGMAP $hostname\n';
      }
    }